name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    
    - name: Install Leiningen
      run: |
        wget -O lein https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
        chmod +x lein
        sudo mv lein /usr/local/bin/
        lein version
    
    - name: Install clj-kondo
      run: |
        curl -sLO https://raw.githubusercontent.com/borkdude/clj-kondo/master/script/install-clj-kondo
        chmod +x install-clj-kondo
        sudo ./install-clj-kondo
    
    - name: Run tests
      run: lein test
    
    - name: Run linting
      run: clj-kondo --lint src test